###
GET http://localhost:9999/customers/3 HTTP/1.1

###
GET http://localhost:9999/customers HTTP/1.1

###
POST http://localhost:9999/customers HTTP/1.1
Content-Type: "application/json"

{
    "id": 0,
    "name": "Vitya",
    "phone": "+992000000041"
}

###
POST http://localhost:9999/customers HTTP/1.1
Content-Type: "application/json"

{
    "id": 2,
    "name": "Vitya",
    "phone": "+992000000022"
}

###
DELETE http://localhost:9999/customers/2 HTTP/1.1

###
POST http://localhost:9999/customers/block/4 HTTP/1.1

###
DELETE http://localhost:9999/customers/unblock/4 HTTP/1.1